name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        # Get the latest version of Trivy
        TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
        wget https://github.com/aquasecurity/trivy/releases/download/${TRIVY_VERSION}/trivy_${TRIVY_VERSION#v}_Linux-64bit.deb
        sudo dpkg -i trivy_${TRIVY_VERSION#v}_Linux-64bit.deb
        trivy --version  # Verify installation

    - name: Build Docker image
      run: |
        docker build -t my-portfolio-image:latest .  # Replace with your image name

    - name: Run Trivy scan
      run: |
        trivy image --output trivy-report.json --severity HIGH,CRITICAL my-portfolio-image:latest  # Scan the image

    - name: Upload Trivy report
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: trivy-report
        path: trivy-report.json  # Path to the generated report

    - name: Run Docker container
      run: |
        docker run -d -p 8080:80 my-portfolio-image:latest  # Replace ports as needed

    - name: Post successful build message
      run: echo "Docker image built and running on localhost:8080"
