name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-portfolio-image:latest .  # Replace with your image name

    - name: Run Trivy scan
      run: |
        trivy image --output trivy-report.json --severity HIGH,CRITICAL my-portfolio-image:latest  # Scan the image

    - name: Upload Trivy report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: trivy-report.json  # Path to the generated report

    - name: Run Docker container
      run: |
        docker run -d -p 8080:80 my-portfolio-image:latest  # Replace ports as needed

    - name: Post successful build message
      run: echo "Docker image built and running on localhost:8080"
